name: Build SunamoPlatformUwpInterop

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    name: Build SunamoPlatformUwpInterop
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoPlatformUwpInterop/SunamoPlatformUwpInterop.csproj

    - name: Build
      run: dotnet build SunamoPlatformUwpInterop/SunamoPlatformUwpInterop.csproj --configuration Release --no-restore

  test:
    name: Test SunamoPlatformUwpInterop.Tests
    runs-on: ${{ matrix.os }}
    needs: build

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoPlatformUwpInterop.Tests/SunamoPlatformUwpInterop.Tests.csproj

    - name: Build tests
      run: dotnet build SunamoPlatformUwpInterop.Tests/SunamoPlatformUwpInterop.Tests.csproj --configuration Release --no-restore

    - name: Run tests
      run: dotnet test SunamoPlatformUwpInterop.Tests/SunamoPlatformUwpInterop.Tests.csproj --configuration Release --no-build --verbosity normal
      continue-on-error: true
